### ISSUE TITLE
\cite not work

### ISSUE THREAD

**Issue by hyzhou404** [let-def/texpresso#45] opened 2024-03-30 07:23 UTC
Thank you for the amazing project!

But I meet problems in citation. I use \cite to cite references in .bib file. References can't be found in TeXpresso. The same project works well in Overleaf.

**Comment by let-def** [comment] 2024-03-30 07:25
TeXpresso only runs LaTeX at the moment, not BibTeX.

The citations need to be built separately, for instance by compiling your file with tectonic. See https://github.com/let-def/texpresso/issues/40.

**Comment by let-def** [comment] 2024-03-30 07:58
In case you are not familiar with the build process of LaTeX, the different tools, including LaTeX itself, produce auxiliary files, which can be picked up later.
TeXpresso will use files produced by BibTeX and the citation should be displayed correctly, it's just that this part is not interactive.

After updating the auxiliary files, you can tell the viewer to pick up the changes by sending signal SIGUSR1, e.g. `killall -SIGUSR1 texpresso` should do the job. This is still experimental and I will document the process later. Don't hesitate to report related issues.

**Comment by hyzhou404** [comment] 2024-03-30 12:01
Apart from updating .bib files, I think TeXpresso doesn't build .bib file correctly in the first compiling time. 
I am not an expert of LATEX, but I think in the first compiling time, the auxiliary files should be generated automatically? When execute `texpresso main.tex`, the produced pdf is without references. In other words, texpresso is expected to work the same as overleaf in static compiling scenario, in my opinion.

**Comment by let-def** [comment] 2024-03-30 12:15
TeXpresso doesn't produce any auxiliary files, that's by design. It picks up files produced by an existing build system. Maybe I might revisit this design later, but this maximizes compatibility for now.

If you don't have any build setup yet, recommend that you use the following build command in your editor:
```sh
tectonic -k root_file.tex && killall -SIGUSR1 texpresso
```

tectonic with -k flag produce auxiliary files (bibtex and latex), and look for a fixpoint (repeat the process to solve all references). After that the killall command tells texpresso to load the new auxiliary files.

With this setup, you have texpresso that gives live feedback and tectonic to update the auxiliary files on demand.

**Comment by let-def** [comment] 2024-04-04 03:10
I will close the issue since things are working as expected. Feel free to comment of you have other questions or remarks.

**Closed by let-def** 2024-04-04 03:10 UTC

**Comment by hyzhou404** [comment] 2024-04-04 16:19
Sorry for late response. It works well with command `tectonic -k root_file.tex && killall -SIGUSR1 texpresso`. Thanks a lot!
